let footerRowSlideDataObject = [
  {
    images: `Images/footer-box-img2.jpg`,
    firstPara: `Clazkit Multi-Purpose Kitchen Storage Revoling Tray Cosmetic Organizer Rotating Tray Lazy Susan for Kitchen...`,
    rate: `695`,
    price: `&#8377;999.00`,
    mrp: `FREE Delivery over ₹499.`,
    date: `Get it by <span>Sunday, March 31</span>`,
    free: `Fulfilled by Amazon`,
  },
  {
    images: `Images/historyimg3.jpg`,
    firstPara: `Spartan Shield TouchScreen Guard For Hero Vida V1 Pro | V1 Plus Electric Scooter [7 INCH] Digital Instrument Console Screen Protect...`,
    rate: `45`,
    price: `₹284.00`,
    mrp: `FREE Delivery`,
    date: ``,
    free: ``,
  },
  {
    images: `Images/historyimg4.jpg`,
    firstPara: `Macho 9H Unbreakable Ultra Clear Glossy HD Screen Guard Scratch Protector for EV Vida V1 Plus/Vida V1 Pro...`,
    rate: `46`,
    price: `₹299.00`,
    mrp: `FREE Delivery over ₹499.`,
    date: `Get it by Tuesday, April 2`,
    free: `Fulfilled by Amazon.`,
  },
  {
    images: `Images/historyimg5.jpg`,
    firstPara: `Zealsy Anti Skid Hero VIDA V1 / V1 PRO Foot Floor Mat and Screen Guard 7 Inch Protector for Scooter Combo Pack of 2`,
    rate: `12`,
    price: `₹495.00`,
    mrp: `₹89.00 shipping`,
    date: ``,
    free: ``,
  },
  {
    images: `Images/historyimg6.jpg`,
    firstPara: `ROMEIZ - Two Wheeler - Motercycle - Bike Cover for Hero Vida V1 Pro SCOOTY Bike Cover with Water-Resistant and Dust Proof Premium...`,
    rate: `4`,
    price: `₹347.00`,
    mrp: `FREE Delivery`,
    date: ``,
    free: ``,
  },
  {
    images: `Images/historyimg7.jpg`,
    firstPara: `INOVERA (LABEL) Pool Space Under Sink Plastic Storage Organizer Adjustable Kitchen Rack Holder, White, Tableto...`,
    rate: `1,178`,
    price: `₹834.00`,
    mrp: ``,
    date: `Get it by Sunday, March 31`,
    free: `FREE Delivery by Amazon`,
  },
  {
    images: `Images/historyimg8.jpg`,
    firstPara: `Screen Secure Instrumental Cluster Protector Compatible for Hero Vida V1 Pro and V1 Plus`,
    rate: `24`,
    price: `₹399.00`,
    date: `Get it by Sunday, March 31`,
    mrp: `FREE Delivery over ₹499.`,
    free: `Fulfilled by Amazon.`,
  },
  {
    images: `Images/historyimg9.jpg`,
    firstPara: `Zulay Kitchen Fridge Storage Boxes (Pack of 6), Fridge Organizer with Removable Drain Plate Fridge Storage Containers Keeps Fruit...`,
    rate: `1,645`,
    price: `₹499.00`,
    date: `FREE Delivery`,
    mrp: ``,
    free: ``,
  },
  {
    images: `Images/historyimg10.jpg`,
    firstPara: `Hero Vida V1 Scooter Footmat: Upgrade Your Ride in Style`,
    rate: `13`,
    price: `₹249.00`,
    date: `FREE Delivery`,
    mrp: ``,
    free: ``,
  },
  {
    images: `Images/historyimg9.jpg`,
    firstPara: `Zulay Kitchen Fridge Storage Boxes (Pack of 6), Fridge Organizer with Removable Drain Plate Fridge Storage Containers Keeps Fruit...`,
    rate: `1,645`,
    price: `₹499.00`,
    date: `FREE Delivery`,
    mrp: ``,
    free: ``,
  },
  {
    images: `Images/historyimg4.jpg`,
    firstPara: `Macho 9H Unbreakable Ultra Clear Glossy HD Screen Guard Scratch Protector for EV Vida V1 Plus/Vida V1 Pro...`,
    rate: `46`,
    price: `₹299.00`,
    mrp: `FREE Delivery over ₹499.`,
    date: `Get it by Tuesday, April 2`,
    free: `Fulfilled by Amazon.`,
  },
  {
    images: `Images/historyimg5.jpg`,
    firstPara: `Zealsy Anti Skid Hero VIDA V1 / V1 PRO Foot Floor Mat and Screen Guard 7 Inch Protector for Scooter Combo Pack of 2`,
    rate: `12`,
    price: `₹495.00`,
    mrp: `₹89.00 shipping`,
    date: ``,
    free: ``,
  },
  {
    images: `Images/historyimg6.jpg`,
    firstPara: `ROMEIZ - Two Wheeler - Motercycle - Bike Cover for Hero Vida V1 Pro SCOOTY Bike Cover with Water-Resistant and Dust Proof Premium...`,
    rate: `4`,
    price: `₹347.00`,
    mrp: `FREE Delivery`,
    date: ``,
    free: ``,
  },
  {
    images: `Images/historyimg7.jpg`,
    firstPara: `INOVERA (LABEL) Pool Space Under Sink Plastic Storage Organizer Adjustable Kitchen Rack Holder, White, Tableto...`,
    rate: `1,178`,
    price: `₹834.00`,
    mrp: ``,
    date: `Get it by Sunday, March 31`,
    free: `FREE Delivery by Amazon`,
  },
  {
    images: `Images/historyimg8.jpg`,
    firstPara: `Screen Secure Instrumental Cluster Protector Compatible for Hero Vida V1 Pro and V1 Plus`,
    rate: `24`,
    price: `₹399.00`,
    date: `Get it by Sunday, March 31`,
    mrp: `FREE Delivery over ₹499.`,
    free: `Fulfilled by Amazon.`,
  },
  {
    images: `Images/historyimg9.jpg`,
    firstPara: `Zulay Kitchen Fridge Storage Boxes (Pack of 6), Fridge Organizer with Removable Drain Plate Fridge Storage Containers Keeps Fruit...`,
    rate: `1,645`,
    price: `₹499.00`,
    date: `FREE Delivery`,
    mrp: ``,
    free: ``,
  },
  {
    images: `Images/historyimg10.jpg`,
    firstPara: `Hero Vida V1 Scooter Footmat: Upgrade Your Ride in Style`,
    rate: `13`,
    price: `₹249.00`,
    date: `FREE Delivery`,
    mrp: ``,
    free: ``,
  },
  {
    images: `Images/historyimg9.jpg`,
    firstPara: `Zulay Kitchen Fridge Storage Boxes (Pack of 6), Fridge Organizer with Removable Drain Plate Fridge Storage Containers Keeps Fruit...`,
    rate: `1,645`,
    price: `₹499.00`,
    date: `FREE Delivery`,
    mrp: ``,
    free: ``,
  },
  {
    images: `Images/historyimg7.jpg`,
    firstPara: `INOVERA (LABEL) Pool Space Under Sink Plastic Storage Organizer Adjustable Kitchen Rack Holder, White, Tableto...`,
    rate: `1,178`,
    price: `₹834.00`,
    mrp: ``,
    date: `Get it by Sunday, March 31`,
    free: `FREE Delivery by Amazon`,
  },
  {
    images: `Images/historyimg8.jpg`,
    firstPara: `Screen Secure Instrumental Cluster Protector Compatible for Hero Vida V1 Pro and V1 Plus`,
    rate: `24`,
    price: `₹399.00`,
    date: `Get it by Sunday, March 31`,
    mrp: `FREE Delivery over ₹499.`,
    free: `Fulfilled by Amazon.`,
  },
  {
    images: `Images/historyimg9.jpg`,
    firstPara: `Zulay Kitchen Fridge Storage Boxes (Pack of 6), Fridge Organizer with Removable Drain Plate Fridge Storage Containers Keeps Fruit...`,
    rate: `1,645`,
    price: `₹499.00`,
    date: `FREE Delivery`,
    mrp: ``,
    free: ``,
  },
  {
    images: `Images/historyimg10.jpg`,
    firstPara: `Hero Vida V1 Scooter Footmat: Upgrade Your Ride in Style`,
    rate: `13`,
    price: `₹249.00`,
    date: `FREE Delivery`,
    mrp: ``,
    free: ``,
  },
  {
    images: `Images/historyimg9.jpg`,
    firstPara: `Zulay Kitchen Fridge Storage Boxes (Pack of 6), Fridge Organizer with Removable Drain Plate Fridge Storage Containers Keeps Fruit...`,
    rate: `1,645`,
    price: `₹499.00`,
    date: `FREE Delivery`,
    mrp: ``,
    free: ``,
  },
];