//box content object
let styleFMObject = [
  {
    sfmlh2: 'Up to 60% off | Styles for men',
    sfmlclothimg: 'Images/menstyleimg1.jpg',
    sfmlclothp: 'Clothing',
    fwearimg: 'Images/menstleimg2.jpg',
    fwearp: 'Footwear',
    watchesimg: 'Images/menstyleimg3.jpg',
    watchesp: 'Watches',
    bagsimg: 'Images/menstyleimg5.jpg',
    bagsp: 'Bags & Wallets',
    styleformena: 'End of season sale',
  },
  {
    sfmlh2: 'Appliances for your home',
    sfmlclothimg: 'Images/home1.jpg',
    sfmlclothp: 'Clothing',
    fwearimg: 'Images/home2.jpg',
    fwearp: 'Footwear',
    watchesimg: 'Images/home3.jpg',
    watchesp: 'Watches',
    bagsimg: 'Images/home4.jpg',
    bagsp: 'Bags & Wallets',
    styleformena: 'See more',
  },
  {
    sfmlh2: 'Revamp your home in style',
    sfmlclothimg: 'Images/homestyle1.jpg',
    sfmlclothp: 'Clothing',
    fwearimg: 'Images/homestyle2.jpg',
    fwearp: 'Footwear',
    watchesimg: 'Images/homestyle3.jpg',
    watchesp: 'Watches',
    bagsimg: 'Images/homestyle4.jpg',
    bagsp: 'Bags & Wallets',
    styleformena: 'Explore all',
  },
  {
    sfmlh2: 'Up to 75% off | Headphones',
    sfmlclothimg: 'Images/head1.jpg',
    sfmlclothp: 'Clothing',
    fwearimg: 'Images/head2.jpg',
    fwearp: 'Footwear',
    watchesimg: 'Images/head3.jpg',
    watchesp: 'Watches',
    bagsimg: 'Images/head4.jpg',
    bagsp: 'Bags & Wallets',
    styleformena: 'See all offers',
  },
  {
    sfmlh2: 'Up to 60% off | Styles for women',
    sfmlclothimg: 'Images/women1.jpg',
    sfmlclothp: 'Clothing',
    fwearimg: 'Images/women2.jpg',
    fwearp: 'Footwear',
    watchesimg: 'Images/women3.jpg',
    watchesp: 'Watches',
    bagsimg: 'Images/women4.jpg',
    bagsp: 'Bags & Wallets',
    styleformena: 'End of season sale',
  },
  {
    sfmlh2: 'Discover TVs by your ideal size',
    sfmlclothimg: 'Images/tv1.jpg',
    sfmlclothp: 'Clothing',
    fwearimg: 'Images/tv2.jpg',
    fwearp: 'Footwear',
    watchesimg: 'Images/tv3.jpg',
    watchesp: 'Watches',
    bagsimg: 'Images/tv4.jpg',
    bagsp: 'Bags & Wallets',
    styleformena: 'See all',
  },
  {
    sfmlh2: 'Your home improvement needs',
    sfmlclothimg: 'Images/start1.jpg',
    sfmlclothp: 'Clothing',
    fwearimg: 'Images/start2.jpg',
    fwearp: 'Footwear',
    watchesimg: 'Images/start3.jpg',
    watchesp: 'Watches',
    bagsimg: 'Images/start4.jpg',
    bagsp: 'Bags & Wallets',
    styleformena: 'Explore all',
  },
  {
    sfmlh2: '  Top styles for him',
    sfmlclothimg: 'Images/men1.jpg',
    sfmlclothp: 'Clothing',
    fwearimg: 'Images/men2.jpg',
    fwearp: 'Footwear',
    watchesimg: 'Images/men3.jpg',
    watchesp: 'Watches',
    bagsimg: 'Images/men4.jpg',
    bagsp: 'Bags & Wallets',
    styleformena: 'See all deals',
  },
];
